---
title: "R Notebook"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(readxl)
library(writexl)
library(stringr)
library(lubridate)

library(MAGIS100PM)
```

library(reticulate)
Sys.setenv(RETICULATE_PYTHON = "/Users/jimk/AppData/Local/Microsoft/WindowsApps/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0")
use_python("/Users/jimk/AppData/Local/Microsoft/WindowsApps/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0", required=TRUE)

#```{python}
#print("the")
#python.exe xer_extractor.py -x current
#python.exe reader.py -d -x current -S
#```


```{r}
all <- get.all.schedule("currjbk3")
charges <- get.all.kronos()
people <- get.p6.people(charges, all)
tasks.people <- combine.tasks.people(people, all)
```

```{r}
labor <- bin.labor(tasks.people)
```


```{r}
fte<- FTE.plots(labor$by.day.all%>%filter(code!='other'))
activities<- activities.plot(all$all.data, interval(as.Date('2024-09-01'),as.Date('2025-11-01')),tcost=1)
milestones<- milestones.plot(all$all.data)
resources<- resources.plot(labor$by.week, device="png")
proc<- procurements.plot(all)
```

```{r}
ggsave(resources, filename=paste(base.path,"/hours.png",sep=''), width=24, units='in', device='png')
ggsave(milestones, filename=paste(base.path,'/milestones.png',sep=''), width=12, units='in', device="png")
ggsave(activities, filename=paste(base.path,"/active.pdf",sep=''),units="in", height=12, width=24, device="pdf")
ggsave(fte[[1]], filename=paste(base.path,"/fte_role.png",sep=''),units="in", device="png")
ggsave(fte[[2]], filename=paste(base.path,"/fte_div.png",sep=''),units="in", device="png")

```


```{r}
print(proc$plot)
print(milestones)
print(fte[[1]])
print(fte[[2]])
print(fte[[3]])
print(fte[[4]])
print(resources)
```

```{r}
activities<- activities.plot(all$all.data, interval(as.Date('2024-09-01'),as.Date('2025-11-01')),tcost=1)
```

```{r}
#labor <- bin.labor(tasks.people)

persons.FY23Q34<- labor$by.week.person %>%
  filter(FY==2023)%>%
  filter(week %within% interval('2023-07-01','2023-10-01')) %>%
  group_by(person,FY)%>%
  summarise(hrs=sum(dl.hours)) %>% 
  mutate(ftes=hrs/(1805/4)) %>%
  filter(!is.na(person)) %>%
  left_join(people%>%select(person=role_name, type=rsrc_name, div=DSC),join_by(person) )

persons.FY23<- labor$by.week.person %>%
  filter(FY==2023) %>%
  group_by(person,FY)%>%
  summarise(hrs=sum(dl.hours)) %>% 
  mutate(ftes=hrs/(1805*FY.table['frac'][1,])) %>%
  filter(!is.na(person)) %>%
  left_join(people%>%select(person=role_name, type=rsrc_name),join_by(person) )

tmp.persons<- labor$by.week.person %>%
  filter(FY==2023)

persons.FY24<- labor$by.week.person %>%
  filter(FY==2024) %>%
  group_by(person,FY)%>%
  summarise(hrs=sum(dl.hours)) %>% 
  mutate(ftes=hrs/(1805)) %>%
  filter(!is.na(person)) %>%
  left_join(people%>%select(person=role_name, type=rsrc_name),join_by(person) )

types.FY24<- labor$by.week.type %>%
  filter(FY==2024) %>%
  group_by(type,person, FY)%>%
  summarise(hrs=sum(dl.hours)) %>% 
  mutate(ftes=hrs/(1805)) %>%
  #filter(!is.na(person)) %>%
  left_join(people%>%select(person=role_name, type=rsrc_name, DSC),join_by(type,person) )

tpt.FY<- labor$by.week.person.task %>%
  filter(FY>2022) %>%
  group_by(type,person,task_id, FY)%>%
  summarise(hrs=sum(dl.hours)) %>% 
  mutate(ftes=hrs/(1805)) %>%
  #filter(!is.na(person)) %>%
  left_join(people%>%select(person=role_name, type=rsrc_name, DSC),join_by(type,person)) %>%
  left_join(all$tasks%>%select(task_id, task_name, task_code, target_start_date, target_end_date), by=join_by(task_id))



```
```{r}
all$all.data %>% 
  mutate(yr=fiscal.from.date(target_start), days_float=total_float/8) %>%
  filter(yr>2023) %>%
  select(code, name, target_start, target_end, total_float, total_cost,yr, days_float) %>%
  arrange(target_start) %>%
  view()
```

```{r}
tmp<- charges%>% filter(Timecard.Start>as.Date("2023-03-01")) %>%
  select(d=Timecard.Start, Hours=Hours, Full.Name=Full.Name, taskname,DSC)

tmp.1<- tmp%>% group_by(Full.Name, d) %>% summarise(sum=sum(Hours),.groups='keep')
tmp.2<- tmp%>% arrange(Full.Name, d) %>% group_by(Full.Name) %>% mutate(csum=cumsum(Hours),.groups='keep')

tmp.g1<- ggplot(tmp.1,aes(x=d, y=sum)) + geom_step() + facet_wrap(vars(Full.Name),scales="free_y")
tmp.g2<- ggplot(tmp.2,aes(x=d, y=csum)) + geom_step() + facet_wrap(vars(Full.Name),scales="free_y")
print(tmp.g1)
print(tmp.g2)

ggsave(tmp.g1, filename=paste(base.path,"/HoursByName.pdf",sep=''),units="in", height=12, width=24, device="pdf")
ggsave(tmp.g2, filename=paste(base.path,"/CumuHoursByName.pdf",sep=''),units="in", height=12, width=24, device="pdf")
```
```{r}
btmp<- labor$by.week.person %>% filter(week>=as.Date("2023-03-01")&week<=as.Date("2023-08-17")) %>%
  select(d=week, Hours=dl.hours, Full.Name=person)

btmp.1<- btmp %>% group_by(Full.Name, d) %>% summarise(sum=sum(Hours),.groups='keep')
btmp.2<- btmp%>% arrange(Full.Name, d) %>% group_by(Full.Name) %>% mutate(csum=cumsum(Hours),.groups='keep')

btmp.g1<- ggplot(btmp.1,aes(x=d, y=sum)) + geom_step() + facet_wrap(vars(Full.Name),scales="free_y")
btmp.g2<- ggplot(btmp.2,aes(x=d, y=csum)) + geom_step() + facet_wrap(vars(Full.Name),scales="free_y")
print(btmp.g1)
print(btmp.g2)

ggsave(btmp.g1, filename=paste(base.path,"/P6HoursByName.pdf",sep=''),units="in", height=12, width=24, device="pdf")
ggsave(btmp.g2, filename=paste(base.path,"/P6CumuHoursByName.pdf",sep=''),units="in", height=12, width=24, device="pdf")

```

