---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(readxl)
library(stringr)
library(lubridate)

FY <- function(year)
{
  function(rec)
  {
    (rec$year==(year-1) & rec$month>=9)|(rec$year==year & rec$month<9)
  }
}

fiscal.yr<-function(year, month)
{
  year <- year + ifelse(month>=10,1,0)
}
fiscal.year<-function(recs)
{
  fiscal.yr(recs$year, recs$month)
}
fiscal.month<-function(recs)
{
  recs$month + ifelse(recs$month>=9, -9, +3)
}

fiscal.from.date <- function(rec) 
{ 
  fiscal.yr( year(rec), month(rec) ) 
}
```

```{r}
datepart<-'Dec22WSCurrent'

read.my.file <- function(datepart, tab)
{
  fname<-paste('../extracted/tab_',tab,'_',datepart,'.csv',sep='')
  df <- read.csv(fname)
  df
}

adjust.date <- function(tab, col,ending) 
{ 
  name.s <- paste(col,"_start",ending,sep='')
  name.e <- paste(col,"_end",ending,sep='')
  tab[[name.s]] <- as.Date(tab[[name.s]]) 
  tab[[name.e]] <- as.Date(tab[[name.e]]) 
  tab
}

# these come from XER extractor
taskrsrc<-read.my.file(datepart, 'TASKRSRC')
rsrc<-read.my.file(datepart, "RSRC")
wbs<-read.my.file(datepart, "PROJWBS")
tasks<-read.my.file(datepart,"TASK")
roles<-read.my.file(datepart,"ROLE")
udf.type<-read.my.file(datepart,"UDFTYPE")
udf.value<-read.my.file(datepart,"UDFVALUE")

tasks<-adjust.date(tasks,"target","_date")
tasks<-adjust.date(tasks,"early","_date")
tasks<-adjust.date(tasks,"late","_date")
taskrsrc<-adjust.date(taskrsrc,"target","_date")

# this is a summary of the above out of reader.py -P -d
# it already has the wbs info merged with the tasks
all.data<-read.csv(paste("../output/alltasks_",datepart,".csv",sep=''))
all.paths<-read.csv(paste("../output/allareas_",datepart,".csv",sep=''))
all.data<-adjust.date(all.data,"target","")
all.data<-adjust.date(all.data,"early","")
all.data<-adjust.date(all.data,"late","")

all.data$cost <- as.numeric(all.data$cost)
all.data$cost[is.na(all.data$cost)] <- 0

```

Information about CPM and PERT in R:
https://cran.r-project.org/web/packages/critpath/vignettes/CPMandPERT.html

PERT charts are mentioned here, along with burndown charts:
https://www.projectmanager.com/blog/3-best-project-management-charts
https://www.projectmanager.com/guides/pert-chart

```{r}
ctc.id <- (filter(udf.type, udf_type_label=='user_text1') %>% select(udf_type_id))[[1]]
ctc.recs <- filter(udf.value, udf_type_id==ctc.id) %>% select(task_id=fk_id, ctc=udf_text)

all.data <- left_join(all.data, ctc.recs, by=join_by(task_id))
```

```{r}
task.rsrc<- taskrsrc%>% left_join(rsrc, by=join_by(rsrc_id))
task.rsrc.roles<- task.rsrc %>% left_join(roles, by=join_by(role_id.x==role_id))
tasks.with.all <- task.rsrc.roles %>% left_join(ctc.recs,by=join_by(task_id))
```


```{r}

chg.cols = rep('guess',32)
chg.cols[1]='text'
chg.cols[2]='text'
chg.cols[18]='text'

c3 <- read_excel('../../Kronos Summary Report (By Task)_Q1903_20230305.xlsx', col_types=chg.cols)
c2 <- read_excel('../../Kronos Summary Report (By Task)_Q1903_20230219.xlsx', col_types=chg.cols)
c1 <- read_excel('../../Kronos Summary Report (By Task)_Q1903_20230205.xlsx', col_types=chg.cols)
c0 <- read_excel('../../Kronos Summary Report (By Task)_Q1903_20230130.xlsx', col_types=chg.cols)
all.charges <- bind_rows(bind_rows(bind_rows(c0,c1),c2),c3)
names(all.charges) <- make.names(colnames(all.charges))

tmp<-as.POSIXlt(all.charges$Timecard.Start)
all.charges <- all.charges %>% mutate(year=tmp$year-100+2000,month=tmp$mon)

# add a fiscal year field
all.charges$fiscal.year <- fiscal.year(all.charges)
all.charges$fiscal.month <- fiscal.month(all.charges)
people.by.year<-all.charges%>% filter(!str_detect(Full.Name,"Nah")) %>% group_by(Full.Name,year) %>% summarise(sum(Hours))

all.charges$taskname <- replace(all.charges$Task.Name, all.charges$Task.Name=='MGS D/E Proto SWF', 'MGS D/E Proto SWF-Q')
all.charges$taskname <- replace(all.charges$taskname, all.charges$taskname=='MAGIS-100 Proj Mgmt', 'MAGIS Proj Mgmt-QIS')
all.charges$taskname <- replace(all.charges$taskname, all.charges$taskname=='MGS Civil M&S', 'MGS Civil M&S-Q')
```


```{r}

date.list <- function(a,b,c)
{
  tmp<-seq.Date(from=a, to=b, by='week')
  data.frame(d=floor_date(tmp,unit="week",week_start=7),hours=c/(length(tmp)))
}

date.list.days <- function(a,b,c)
{
  tmp<-seq.Date(from=a, to=b, by='day')
  data.frame(d=floor_date(tmp,unit="day",week_start=7),hours=c/(length(tmp)))
}

```

Need name dataset with the following:

Name, Functional.Role, Job.Functional.Role, Functional.Category, role_name, rsrc_name, rsrc_short_name

```{r}
tmp.kronos.names <- all.charges %>% select(taskname, Function.Role, Job.Functional.Code, Function.Category, Last.Name, Full.Name)
tmp.rsrc.names <- rsrc %>% select(rsrc_id, role_id, rsrc_name, rsrc_short_name, rsrc_type)
tmp.role.names <- roles %>% select(role_id, role_name)
tmp.taskrsrc.names <- taskrsrc %>% select(rsrc_id, rsrc_type, role_id)

people.p6 <- tmp.taskrsrc.names %>% 
  left_join(tmp.role.names, by=join_by(role_id)) %>% 
  left_join(tmp.rsrc.names, by=join_by(rsrc_id)) %>%
  left_join(tmp.kronos.names, by=join_by(role_name==Full.Name)) %>%
  distinct(rsrc_name, role_name, .keep_all = TRUE)

people.p6$rsrc.code<- case_when(
  str_detect(people.p6$rsrc_short_name,"COORD")~'TECH', 
  str_detect(people.p6$rsrc_short_name,"APDEV")~'ENG', 
  str_detect(people.p6$rsrc_short_name,"DRIVE")~'TECH', 
  str_detect(people.p6$rsrc_short_name,"TECH")~'TECH', 
  str_detect(people.p6$rsrc_short_name,"DESIGN")~'ENG', 
  str_detect(people.p6$rsrc_short_name,"PHYST")~'SCI', 
  str_detect(people.p6$rsrc_short_name,"MACHIN")~'TECH', 
  str_detect(people.p6$rsrc_short_name,"DRAFT")~'TECH', 
  str_detect(people.p6$rsrc_short_name,"METRO")~'TECH', 
  str_detect(people.p6$rsrc_short_name,"SPCLST")~'TECH', 
  str_detect(people.p6$rsrc_short_name,"PRJ")~'ADMIN', 
  str_detect(people.p6$rsrc_short_name,"EXP_RA")~'RA', 
  str_detect(people.p6$rsrc_short_name,"SAFE")~'TECH', 
  TRUE~"NONE"
  )

people.p6$rsrc.code[str_detect(people.p6$Last.Name, "KOWALKOW")]='ENG'
people.p6$rsrc.code[str_detect(people.p6$Last.Name, "PLUNK")]='SCI'
people.p6$rsrc.code[str_detect(people.p6$Last.Name, "VALERIO")]='ENG'
people.p6$rsrc.code[str_detect(people.p6$Last.Name, "TEMPLES")]='RA'

tasks.with.all <- tasks.with.all %>%
  left_join(select(people.p6, rsrc_id, role_id.x, rsrc.code), by=join_by(rsrc_id, role_id.x==role_id.x))
  


j.ctc<- bind_rows( distinct(all.charges,taskname), distinct(select(tasks.with.all,ctc), taskname=ctc))

j.ctc$taskname.code<- case_when(
  str_detect(j.ctc$taskname, "Proj")~'Proj', 
  str_detect(j.ctc$taskname, "Civil")~'Civil',
  str_detect(j.ctc$taskname, "Proto")~'Proto',
  str_detect(j.ctc$taskname, "Research")~'Research',
  str_detect(j.ctc$taskname, "Network")~'Network',
  str_detect(j.ctc$taskname, "Qual")~'Qual',
  str_detect(j.ctc$taskname, "Shaft")~'Shaft',
  str_detect(j.ctc$taskname, "Site")~'Site',
  TRUE~'None'
)

```


```{r}
# temporary
#first.week<-as.Date('2023-03-05')

# magic dates - Kronos and scheduled hours almost match in this range.
# Increasing first.week date by one day makes scheduled hours go higher than logged hours.
# It gets much worse as first.week approaches last.week.
first.week<-as.Date('2022-05-08')
last.week<-as.Date('2023-03-08')

#  There are no scheduled hours in this range of dates, but Kronos logged 6131 hours.
#first.week<-as.Date('2019-01-01')
#last.week<-as.Date('2022-05-09')

# Later data
#first.week<-as.Date('2022-12-20')
#last.week<-as.Date('2023-03-08')


#first.week<-as.Date('2019-01-01')
#last.week<-as.Date('2022-10-06')

# FY24
#first.week<-as.Date('2023-10-01')
#last.week<-as.Date('2024-09-30')

# FY23-25
first.week<-as.Date('2023-03-01')
last.week<-as.Date('2025-09-30')


# here I really want the tasks.with.all to have the new rsrc.code from people.p6 
# removed ctc=ctc, from the selection list

by.day<- tasks.with.all %>%
  filter(rsrc_type.x=='RT_Labor') %>%
  select( task_id=task_id,s=target_start_date, e=target_end_date, dt=target_qty, r=remain_qty,  rsrc=rsrc_short_name, code=rsrc.code) %>%
  #filter(!is.na(ctc)&str_detect(ctc,".*")) %>% 
  rowwise() %>% mutate(dl=list(date.list.days(s,e,dt)))

by.day2<- unnest(by.day,cols=c(dl),names_sep='.') %>% arrange(s) %>%
  mutate(week=floor_date(dl.d,unit="week",week_start=1)) %>%
  mutate(FY=fiscal.from.date(week))

by.day3<- by.day2 %>% 
  filter(week<last.week & week>first.week)%>%
  group_by(FY, code, week) %>% summarise(hsum=sum(dl.hours))
print('-')

by.week4<- by.day3 %>%
  arrange(FY,code,week)%>%
  group_by(FY,code) %>% mutate(csum=cumsum(hsum))

print('-')

by.kronos4<- all.charges%>%
  filter(Timecard.Start<last.week & Timecard.Start>first.week)%>%
  select(Last.Name, taskname, Timecard.Start, Hours)%>%
  arrange(taskname, Timecard.Start)%>%
  group_by(taskname) %>% mutate(ksum=cumsum(Hours))

```

```{r}

by.kronos4.j <- left_join(by.kronos4, j.ctc, by=join_by(taskname))  
by.week4.j <- left_join(by.week4.j, j.ctc, by=join_by(ctc==taskname))

by.both4.j <- full_join(by.week4.j, by.kronos4.j, by=join_by(taskname.code, week==Timecard.Start))

tmp.ctc.hours<-by.day3%>%
  filter(week<last.week & week>first.week)%>%
  group_by(ctc) %>%summarise(tot=sum(hsum)) 

tmp.kronos.hours<-all.charges%>%
  filter(Timecard.Start>first.week & Timecard.Start<last.week)%>%
  group_by(taskname)%>%summarise(tot=sum(Hours))

#view(tmp.ctc.hours)
#view(tmp.kronos.hours)

s.k<-sum(tmp.kronos.hours$tot)
s.c<-sum(tmp.ctc.hours$tot)
print(s.k)
print(s.c)
print(s.k-s.c)
```


```{r}
t.2<-ggplot(by.week4,aes(x=week, y=hsum,colour=as.factor(FY))) +
  scale_x_date(date_breaks='1 weeks', date_labels = "%d %b %y") +
  theme(axis.text.x = element_text(angle = 90)) +
  geom_step() + facet_grid(vars(code), scales="free_y")

#t.2<-ggplot(by.both4,aes(x=week, y=csum,colour=as.factor(g))) +
#  scale_x_date(date_breaks='1 weeks', date_labels = "%d %b %y") +
#  theme(axis.text.x = element_text(angle = 90)) +
#  geom_step() + facet_grid(vars(g), scales="free_y")

print(t.2)
ggsave(t.2, filename="hours3.pdf",units="in", height=10, width=24, device="pdf")

```

