---
title: "R Notebook"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(readxl)
library(writexl)
library(stringr)
library(rlang)
library(lubridate)

library(MAGIS100PM)
```


```{r}
all.orig <- get.all.schedule("WS2503")
all <- apply.baseline.schedule(all.orig, "BL2412")

filt.st<-as.Date("2024-10-01")
filt.en<-as.Date("2025-10-01")
filt.asof<- filt.st
filt.name<- "AllPlots"

```

```{r}
charges <- get.all.kronos()
people <- get.p6.people(charges, all)
tasks.people <- combine.tasks.people(people, all)

labor <- bin.labor(tasks.people)
costs <- bin.expenses(all$all.data)
costs.week <- costs$target.by.week%>% filter(FY>=2025&FY<2028)%>%group_by(FY)%>%mutate(csum=cumsum(hsum))
```

The resources plot is the one that produces the resource leveling plot per job function

```{r}
fte<- FTE.plots(labor$by.day.all%>%filter(code!='other'))
activities<- activities.plot(all$all.data, start.date=filt.st,end.date=filt.en)
milestones<- milestones.plot(all$all.data, exclude.future=FALSE, earliest.date=filt.st, latest.date=filt.en)
resources<- resources.plot(labor$by.week, device="pdf")
proc<- procurements.plot(all, en=Sys.Date()+weeks(8*4))
reviews<- reviews.plot(all$all.data, start.date=filt.st, end.date=filt.st+months(6))
```

```{r}
ggsave(resources, filename=paste(base.path,"/output/hours.png",sep=''), width=24, units='in', device='png')
ggsave(milestones, filename=paste(base.path,'/output/milestones.png',sep=''), width=11, units='in', device="png")
#ggsave(activities, filename=paste(base.path,"/output/active.pdf",sep=''),width=12, height=10, units="in", device="pdf")
#ggsave(reviews, filename=paste(base.path,"/output/reviews.pdf",sep=''),units="in", width=11, device="pdf")
#ggsave(proc$plot, filename=paste(base.path,"/output/procurements.pdf",sep=''),units="in", width=16, device="pdf")
ggsave(fte[[1]], filename=paste(base.path,"/output/fte_role.png",sep=''),units="in", device="png")
ggsave(fte[[2]], filename=paste(base.path,"/output/fte_div.png",sep=''),units="in", device="png")

```


```{r}
#print(proc$plot)
#print(milestones)
#print(fte[[1]])
#print(fte[[2]])
#print(fte[[3]])
#print(fte[[4]])
print(resources)
#print(activities)
#print(reviews)
```

#```{r}
#activities<- activities.plot(all$all.data, interval(as.Date('2024-09-01'),as.Date('2025-11-01')),tcost=1)
#```


This is a test for plotting over the T2 milestones
```{r}
milestones<- milestones.filter(all$all.data%>%filter(str_detect(name,"T2 ")),exclude.future=FALSE,
                               earliest.date = as.Date("2023-03-01"), latest.date = as.Date("2025-02-01"))
max_end<- tmp %>% slice_max(target_end,n=1,with_ties = FALSE) %>% pull(target_end)
min_end<- tmp %>% slice_min(target_end,n=1,with_ties = FALSE) %>% pull(target_end)


gp3<-ggplot(
    milestones,
    aes( colour=  state, x=target_end, y=reorder(code,target_start))
  ) +
    geom_point(size=1) +
    geom_text(aes(hjust='left',label = paste(short_name, ' (', total_float/8,')', sep='')),
              nudge_x=9.6) +
    scale_x_date(date_breaks='3 month', date_labels = "%b %y",
                 limits=c(min_end, max_end)) +
    theme(axis.text.x = element_text(angle = 90), legend.position = "top") +
    labs(x="Forecast End Date", y="Milestone", colour="State")

fac=.5
ggsave(gp3, filename=paste(base.path,'/output/milestonesS.pdf',sep=''),height=15*fac, width=14*fac,units='in', device="pdf")
#print(gp3)

```

This is a function to pull out important fields with a filter

```{r}

tmp.simpler <- all$all.data %>%
  select(code, name, total_float, target_start, target_end, start, finish, wbs, wbs_high, wbs_low) %>% 
  mutate(total_float=total_float/8) %>% 
  filter(total_float < 40, target_start>=now()) %>% 
  arrange(target_start, total_float, wbs) # %>% view()

#write_xlsx(tmp.simpler, "low_float.xlsx")
tmp.variances <- read_xlsx("../variancesFY25Q1.xlsx")
tmp.simpler4 <- tmp.variances %>% left_join(tmp.simpler, by=join_by(ActivityID==code))

#all$all.data %>% select(code, name, total_float, target_start, target_end, wbs, wbs_high, wbs_low) %>% mutate(total_float=total_float/8) %>% filter( target_start>=now()) %>% arrange(target_start, total_float, wbs) %>% view()

```


```{r}

tmp.simpler2 <- all$all.data %>%
  select(code, name, total_float, target_start, target_end, start, finish, wbs, total_cost) %>%
  mutate(total_float=total_float/8) %>% 
  filter(total_cost>100000, target_start>=now()) %>%
  arrange(target_start, total_float, wbs) %>%
  view("proc")

#write_xlsx(tmp.simpler, "high_cost.xlsx")
#tmp.variances <- read_xlsx("../variancesFY25Q1.xlsx")

```

```{r}
tmp.simpler3 <- all$all.data %>%
  filter(target_start>=now(),str_detect(name,"Procure"),target_end<=as.Date("2026-01-07")) %>%
  select(code, name, total_float, target_start, target_end, start, finish, wbs, total_cost, wbs_low) %>% 
  mutate(total_float=total_float/8) %>%arrange(target_end) %>% view()

#write_xlsx(tmp.simpler3, "procurements.xlsx")

```

```{r}

tmp.simpler4 <- all$all.data %>%
  select(code, name, total_float, target_start, target_end, start, finish, wbs, wbs_high, wbs_low) %>% 
  mutate(total_float=total_float/8)  %>% 
  arrange(target_start, total_float, wbs) # %>% view()

tmp.variances <- read_xlsx("../variancesFY25Q1.xlsx")
tmp.simpler4 <- tmp.variances %>% left_join(tmp.simpler4, by=join_by(ActivityID==code))

```


```{r}

tmp.simpler4 <- all$all.data %>% 
  select(code, name, total_float, target_start, target_end, expected_end, start, finish, actual_start, actual_end, wbs, wbs_high, wbs_low, status) %>%
  mutate(total_float=total_float/8)  %>% 
  arrange(target_end, total_float, wbs) %>%
  #filter(total_float<80) %>% 
  #filter(target_end < as.Date("2025-12-31") & target_end > as.Date("2025-03-01")) %>%
  #filter(str_detect(wbs,"00.")) %>%
  #filter(str_detect(name, "Source")) %>% 
  view()


```

