---
title: "R Notebook"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(readxl)
library(writexl)
library(stringr)
library(rlang)
library(lubridate)

library(MAGIS100PM)
```



```{r}
all <- get.all.schedule("WS2309")
charges <- get.all.kronos()
people <- get.p6.people(charges, all)
tasks.people <- combine.tasks.people(people, all)
```

```{r}
labor <- bin.labor(tasks.people)
costs <- bin.expenses(all$all.data)
costs.week <- costs$target.by.week%>% filter(FY>=2023&FY<2028)%>%group_by(FY)%>%mutate(csum=cumsum(hsum))
```


Full.Name = Full.Name
Full.Name = Role

```{r}
kr.proc <- function(grouping.name, charges)
{
  grouping.sym = rlang::sym(grouping.name)

  kr.tmp<- charges %>% filter(Timecard.Start>as.Date("2023-03-01")) %>%
    select(FY=fiscal.year, d=Timecard.Start, Hours=Hours, Full.Name=Full.Name,ctc=taskcode,department=DSC, role=Role) %>%
    mutate(LOE=ctc=='Q1903.01') %>%
    mutate(role.new=if_else(LOE=='TRUE'&!is.na(ctc), "LOE", role))

  kr.tmp.1<- kr.tmp%>% group_by(ctc, !!grouping.sym, d) %>% summarise(sum=sum(Hours),.groups='keep')
  kr.tmp.2<- kr.tmp.1%>% arrange(ctc, !!grouping.sym, d) %>% group_by(ctc, !!grouping.sym) %>% mutate(csum=cumsum(sum))
  kr.tmp.1<- rename(kr.tmp.1, grouping=grouping.name)
  kr.tmp.2<- rename(kr.tmp.2, grouping=grouping.name)

  kr.tmp.g1<- ggplot(kr.tmp.1,aes(x=d, y=sum)) + geom_step() + facet_wrap(vars(ctc,grouping),scales="free_y")
  kr.tmp.g2<- ggplot(kr.tmp.2,aes(x=d, y=csum)) + geom_step() + facet_wrap(vars(ctc,grouping),scales="free_y")

  list(kr=kr.tmp, kr1=kr.tmp.1, kr2=kr.tmp.2, kr.g1=kr.tmp.g1, kr.g2=kr.tmp.g2)
}

p6.proc <- function(grouping.name, labor.by.week)
{
  grouping.sym = rlang::sym(grouping.name)
  
  p6.tmp<- labor.by.week %>% filter(week>=as.Date("2023-03-01")&week<=as.Date("2024-01-01")) %>%
    select(FY=FY, d=week, Hours=dl.hours, Full.Name=person, department=code, ctc=ctc, role=Role) %>%
    mutate(LOE=ctc=='Q1903.01')%>%
    mutate(role.new=if_else(LOE=='TRUE'&role!="RA", "LOE", role))

  p6.tmp.1<- p6.tmp %>% group_by(ctc, !!grouping.sym, d) %>% summarise(sum=sum(Hours),.groups='keep')
  p6.tmp.2<- p6.tmp.1%>% arrange(ctc, !!grouping.sym, d) %>% group_by(ctc, !!grouping.sym) %>% mutate(csum=cumsum(sum))
  p6.tmp.1<- rename(p6.tmp.1, grouping=grouping.name)
  p6.tmp.2<- rename(p6.tmp.2, grouping=grouping.name)

  p6.tmp.g1<- ggplot(p6.tmp.1,aes(x=d, y=sum)) + geom_step() + facet_wrap(vars(ctc,grouping),scales="free_y")
  p6.tmp.g2<- ggplot(p6.tmp.2,aes(x=d, y=csum)) + geom_step() + facet_wrap(vars(ctc,grouping),scales="free_y")
  
  list(p6=p6.tmp, p61=p6.tmp.1, p62=p6.tmp.2, p6.g1=p6.tmp.g1, p6.g2=p6.tmp.g2)
}

```

Full.Name = person
Full.Name = Role

labor$by.week.person
labor$by.week.role


```{r}

#kr.data <- kr.proc("role.new", charges%>%filter(taskname=="Q1903.10"))
kr.data <- kr.proc("role.new", charges)
p6.data <- p6.proc("role.new", labor$by.week.ctc) # role
```


#```{r}
print(kr.data$kr.g1)
print(kr.data$kr.g2)

ggsave(kr.data$kr.g1, filename=paste(base.path,"/HoursByName.pdf",sep=''),units="in", height=12, width=24, device="pdf")
ggsave(kr.data$kr.g2, filename=paste(base.path,"/CumuHoursByName.pdf",sep=''),units="in", height=12, width=24, device="pdf")
# ```

#```{r}
print(p6.data$p6.g1)
print(p6.data$p6.g2)

ggsave(p6.data$p6.g1, filename=paste(base.path,"/P6HoursByName.pdf",sep=''),units="in", height=12, width=24, device="pdf")
ggsave(p6.data$p6.g2, filename=paste(base.path,"/P6CumuHoursByName.pdf",sep=''),units="in", height=12, width=24, device="pdf")

#```

```{r}
#person.diff <- setdiff(unique(charges$Full.Name), unique(labor$by.week.person$person))
person.comp <- rbind(mutate(p6.data$p62,from="P6"),mutate(kr.data$kr2,from="KR"))
  #left_join(mutate(tmp.2,from="KR"), by=join_by(Full.Name,d), suffix=c(".p6",".kr"))

# mutate(d=ceiling_date(d, unit="month"))%>%
# group_by(FY,from, ctc,week)%>%summarise(sum=sum(sum), csum=sum(csum))

#person.comp.p <- pivot_wider(person.comp, names_from=c("from"), values_from = c("sum","csum"))
#person.comp.p <- full_join(person.comp%>%filter(from=="KR"),person.comp%>%filter(from=="P6"), by=join_by(d,ctc,grouping), 

person.comp.p <- person.comp %>% filter(d<as.Date("2023-10-01")) %>% 
  group_by(from,d,grouping) %>% summarise(sum=sum(sum), csum=sum(csum))
person.comp.p <- full_join(person.comp.p%>%filter(from=="KR"),person.comp.p%>%filter(from=="P6"), by=join_by(d,grouping), suffix=c(".KR",".P6")) %>% 
  mutate(sum.KR=replace_na(sum.KR,0), sum.P6=replace_na(sum.P6,0)) %>%
  mutate(csum.KR=replace_na(csum.KR,0), csum.P6=replace_na(csum.P6,0))

person.g3p<- ggplot(person.comp.p,aes(x=d)) + 
  geom_step(aes(y=csum.KR, colour=from.KR)) +
  geom_step(aes(y=csum.P6, colour=from.P6)) +
  scale_x_date(name="Date (by month)", date_breaks='1 month', date_labels = "%b %y") +
  facet_wrap(vars(grouping),scales="free_y") + 
  #facet_wrap(vars(ctc,grouping),scales="free_y") + 
  theme(axis.text.x = element_text(angle = 90))
person.g3pb<- ggplot(person.comp.p,aes(x=d, y=(csum.KR-csum.P6))) + 
  geom_step() +
  scale_x_date(name="Date (by month)", date_breaks='1 month', date_labels = "%b %y") +
  facet_wrap(vars(grouping),scales="free_y") + 
  #facet_wrap(vars(ctc,grouping),scales="free_y") + 
  theme(axis.text.x = element_text(angle = 90))

print(person.g3p)
print(person.g3pb)


person.g3<- ggplot(person.comp,aes(x=d, colour=from)) + 
  geom_step(aes(y=csum)) +
  scale_x_date(name="Date (by month)", date_breaks='1 month', date_labels = "%b %y") +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(vars(ctc,grouping),scales="free_y")

print(person.g3)
ggsave(person.g3, filename=paste(base.path,"output/CumuHoursByRole.pdf",sep=''),units="in", height=12, width=24, device="pdf")

tmp<- person.comp %>% ungroup() %>% select(from, d, isum=sum) %>% group_by(from,d)%>% summarise(sum=sum(isum)) %>% arrange(from, d) %>% group_by(from) %>% mutate(csum=cumsum(sum))

person.g4<- ggplot(tmp,aes(x=d, colour=from)) + 
  geom_step(aes(y=csum)) +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_x_date(name="Date (by month)", date_breaks='1 month', date_labels = "%b %y")

#  geom_step(aes(y=csum)) +
#  facet_wrap(vars(from),scales="free_y")
print(person.g4)
```
```{r}
ctc.comp <- rbind(mutate(p6.data$p6,from="P6"),mutate(kr.data$kr,from="KR"))

tmp<- ctc.comp %>% ungroup() %>% select(from, FY, ctc, d, Hours) %>% group_by(FY,from,ctc,d)%>% summarise(sum=sum(Hours)) %>% arrange(FY, from, ctc, d) %>% group_by(FY, from, ctc) %>% mutate(csum=cumsum(sum))

ctc.g5b<- ggplot(tmp%>%filter(FY==2023)%>% mutate(week=ceiling_date(d, unit="month"))%>%group_by(FY,from, ctc,week)%>%summarise(tot=sum(sum)),
                 aes(x=week, colour=from)) + 
  geom_step(aes(y=tot)) +
#  geom_step(aes(y=csum)) +
  facet_wrap(vars(FY,ctc),scales="free_y", nrow=1) +
  scale_x_date(name="Date (by month)", date_breaks='1 month', date_labels = "%b %y") +
  #scale_y_continuous(name="cumulative costs", n.breaks=6) +
        theme(axis.text.x = element_text(angle = 90))
print(ctc.g5b)



ctc.g5<- ggplot(tmp,aes(x=d, colour=from)) + 
  geom_step(aes(y=csum)) +
#  geom_step(aes(y=csum)) +
  facet_wrap(vars(FY,ctc),scales="free_y")
print(ctc.g5)

tmp2<- ctc.comp %>% ungroup() %>% select(from, FY, name=role.new, d, Hours) %>% group_by(FY,from,name,d)%>% summarise(sum=sum(Hours)) %>% arrange(FY, from, name, d) %>% group_by(FY, from, name) %>% mutate(csum=cumsum(sum))

person.g6<- ggplot(tmp2,aes(x=d, colour=from)) + 
  geom_step(aes(y=csum)) +
#  geom_step(aes(y=csum)) +
  facet_wrap(vars(FY,name),scales="free_y")
print(person.g6)


```


```{r}
k<- kr.proc("Full.Name", charges)
tmpp<- ggplot(k$kr2, aes(x=d, colour=ctc)) + geom_step(aes(y=csum)) + facet_wrap(vars(grouping), scales="free_y", ncol=4)
ggsave("../output/kr2_cyc.pdf", tmpp)
print(tmpp)
```
