---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE, warning=TRUE}
library(tidyverse)
library(ggplot2)
library(readxl)
library(writexl)
library(stringr)
library(lubridate)

library(MAGIS100PM)
```


```{r}

sched_name <- "WS2309"
all <- get.all.schedule(sched_name)

alldata<- all$all.data %>% filter(dur>0) %>%
  filter(target_start>as.Date('2022-10-01')) 
```



```{r}
library(timevis)
tl<-read_excel("timeline.xlsx")
groups = data.frame(id = 1:3, content = c("Boundaries", "Early Measurement", "Key Activities"))
tmp<- timevis(tl, groups=groups)
htmlwidgets::saveWidget(tmp, "myTimeLine.html", selfcontained = F)
print(tmp)
```


tl <- data.frame(
  start=c("2023-10-01", "2023-11-01", "2024-01-01",
          "2024-10-01", "2025-01-01", "2025-07-01", 
          "2025-10-01", "2026-01-01", "2026-05-01", "2026-05-12", "2026-09-15",
          "2026-10-01", "2026-10-08", "2026-12-02", "2027-01-01"),
  end=c(NA, "2025-06-06", NA,
        NA, NA, "2026-08-01",
        NA, NA, "2026-06-01", "2026-08-01", NA,
        NA, "2026-12-01", "2027-04-02", NA ),
  content=c("FY24", "Prototype@Stanford", "Cy24",
            "FY25", "CY25", "FNAL Test stand", 
            "FY26", "CY26", "Shaft crane/electric", "Shaft wall brackets", "Modular section assembly complete",
            "FY27", "install Modular Sections", "Testing", "CY27"),
  id=c(1:15)
  )

  timevis(tl)
#```





